name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Find & Restore
      run: |
        FILE=$(find . -name "*.csproj" | head -n 1)
        echo "Found project: $FILE"
        dotnet restore "$FILE"

    - name: Find & Build
      run: |
        FILE=$(find . -name "*.csproj" | head -n 1)
        dotnet build "$FILE" --no-restore

  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Find frontend + build
      run: |
        if [ -f "frontend/package.json" ]; then
          cd frontend
        elif [ -f "package.json" ]; then
          echo "frontend in root"
        else
          echo "No frontend found"
          exit 0
        fi

        npm install
        npm run build
